import type { Connection } from "../state/types";

/**
 * Small hand-picked demo edge set — stands in for GraphEngine's real depends_on_ids data
 * (src/codechroma/engine.py get_dependencies/get_dependents) until the real bridge exists. Kept
 * separate from fixtures.ts, which is machine-regenerated by scripts/export_examples_fixture.py.
 */
export const FIXTURE_CONNECTIONS: Connection[] = [
  {
    from_id: "file::shadow-app/backend/routers/orders_router.py",
    to_id: "file::shadow-app/backend/domain/order_service.py",
  },
  {
    from_id: "file::shadow-app/backend/routers/users_router.py",
    to_id: "file::shadow-app/backend/domain/user_service.py",
  },
];
