import type { HierarchyLevel, HierarchyNodeRef } from "../state/types";

export interface FixtureNode extends HierarchyNodeRef {
  children: string[];
}

function node(
  node_id: string,
  name: string,
  level: HierarchyLevel,
  parent_id: string | null,
  children: string[],
  extra?: { params?: string; source?: string; language?: string },
): FixtureNode {
  return {
    node_id,
    name,
    level,
    parent_id,
    has_children: children.length > 0,
    child_count: children.length,
    children,
    ...extra,
  };
}

/**
 * Folder/file fixture hierarchy, generated by `scripts/export_examples_fixture.py` from a
 * plain filesystem walk over `examples/` -- not hand-authored. Re-run that script after
 * adding or changing files under `examples/`.
 */
export const FIXTURE_NODES: Record<string, FixtureNode> = {
  "root": node("root", "examples", "folder", null, ["folder::shadow-app", "folder::billing-lite"]),
  // A second, minimal top-level project alongside shadow-app -- root's two real top-level children,
  // needed so a real browser can exercise multi-select group-drag and box-vs-box collision on the
  // hierarchy's own boxes strategy (see e2e/multi-select.spec.ts, e2e/block-collision.spec.ts;
  // 016-single-canvas-dashboard Stage 4 retired the C1-boxes-based versions of both, since a C1
  // recipe box on the one canvas deliberately doesn't join the collision/multi-select system).
  "folder::billing-lite": node("folder::billing-lite", "billing-lite", "folder", "root", []),
  "folder::shadow-app": node("folder::shadow-app", "shadow-app", "folder", "root", ["folder::shadow-app/backend", "folder::shadow-app/frontend"]),
  "folder::shadow-app/backend": node("folder::shadow-app/backend", "backend", "folder", "folder::shadow-app", ["folder::shadow-app/backend/clients", "file::shadow-app/backend/config.py", "file::shadow-app/backend/dependencies.py", "folder::shadow-app/backend/domain", "file::shadow-app/backend/main.py", "folder::shadow-app/backend/models", "folder::shadow-app/backend/repositories", "folder::shadow-app/backend/routers"]),
  "folder::shadow-app/backend/clients": node("folder::shadow-app/backend/clients", "clients", "folder", "folder::shadow-app/backend", ["file::shadow-app/backend/clients/email_client.py", "file::shadow-app/backend/clients/payment_client.py"]),
  "file::shadow-app/backend/clients/email_client.py": node("file::shadow-app/backend/clients/email_client.py", "email_client.py", "file", "folder::shadow-app/backend/clients", ["class::EmailClient"]),
  "file::shadow-app/backend/clients/payment_client.py": node("file::shadow-app/backend/clients/payment_client.py", "payment_client.py", "file", "folder::shadow-app/backend/clients", ["class::PaymentClient"]),
  "file::shadow-app/backend/config.py": node("file::shadow-app/backend/config.py", "config.py", "file", "folder::shadow-app/backend", ["class::Settings"]),
  "file::shadow-app/backend/dependencies.py": node("file::shadow-app/backend/dependencies.py", "dependencies.py", "file", "folder::shadow-app/backend", ["function::get_db", "function::get_current_user"]),
  "folder::shadow-app/backend/domain": node("folder::shadow-app/backend/domain", "domain", "folder", "folder::shadow-app/backend", ["file::shadow-app/backend/domain/order_service.py", "file::shadow-app/backend/domain/user_service.py"]),
  "file::shadow-app/backend/domain/order_service.py": node("file::shadow-app/backend/domain/order_service.py", "order_service.py", "file", "folder::shadow-app/backend/domain", ["function::calculate_total", "function::apply_discount"]),
  "file::shadow-app/backend/domain/user_service.py": node("file::shadow-app/backend/domain/user_service.py", "user_service.py", "file", "folder::shadow-app/backend/domain", ["function::register_user", "function::authenticate_user"]),
  "file::shadow-app/backend/main.py": node("file::shadow-app/backend/main.py", "main.py", "file", "folder::shadow-app/backend", ["function::create_app", "function::main"]),
  "folder::shadow-app/backend/models": node("folder::shadow-app/backend/models", "models", "folder", "folder::shadow-app/backend", ["file::shadow-app/backend/models/formatting.py", "file::shadow-app/backend/models/order.py", "file::shadow-app/backend/models/user.py"]),
  "file::shadow-app/backend/models/formatting.py": node("file::shadow-app/backend/models/formatting.py", "formatting.py", "file", "folder::shadow-app/backend/models", ["function::format_currency"]),
  "file::shadow-app/backend/models/order.py": node("file::shadow-app/backend/models/order.py", "order.py", "file", "folder::shadow-app/backend/models", ["class::Order"]),
  "file::shadow-app/backend/models/user.py": node("file::shadow-app/backend/models/user.py", "user.py", "file", "folder::shadow-app/backend/models", ["class::User"]),
  "folder::shadow-app/backend/repositories": node("folder::shadow-app/backend/repositories", "repositories", "folder", "folder::shadow-app/backend", ["file::shadow-app/backend/repositories/base.py", "file::shadow-app/backend/repositories/order_repository.py", "file::shadow-app/backend/repositories/user_repository.py"]),
  "file::shadow-app/backend/repositories/base.py": node("file::shadow-app/backend/repositories/base.py", "base.py", "file", "folder::shadow-app/backend/repositories", ["class::BaseRepository"]),
  "file::shadow-app/backend/repositories/order_repository.py": node("file::shadow-app/backend/repositories/order_repository.py", "order_repository.py", "file", "folder::shadow-app/backend/repositories", ["class::OrderRepository"]),
  "file::shadow-app/backend/repositories/user_repository.py": node("file::shadow-app/backend/repositories/user_repository.py", "user_repository.py", "file", "folder::shadow-app/backend/repositories", ["class::UserRepository"]),
  "folder::shadow-app/backend/routers": node("folder::shadow-app/backend/routers", "routers", "folder", "folder::shadow-app/backend", ["file::shadow-app/backend/routers/orders_router.py", "file::shadow-app/backend/routers/users_router.py"]),
  "file::shadow-app/backend/routers/orders_router.py": node("file::shadow-app/backend/routers/orders_router.py", "orders_router.py", "file", "folder::shadow-app/backend/routers", ["function::list_orders", "function::create_order"]),
  "file::shadow-app/backend/routers/users_router.py": node("file::shadow-app/backend/routers/users_router.py", "users_router.py", "file", "folder::shadow-app/backend/routers", ["function::list_users", "function::create_user"]),
  "folder::shadow-app/frontend": node("folder::shadow-app/frontend", "frontend", "folder", "folder::shadow-app", ["folder::shadow-app/frontend/src"]),
  "folder::shadow-app/frontend/src": node("folder::shadow-app/frontend/src", "src", "folder", "folder::shadow-app/frontend", ["file::shadow-app/frontend/src/App.tsx", "folder::shadow-app/frontend/src/api", "folder::shadow-app/frontend/src/components", "folder::shadow-app/frontend/src/domain", "file::shadow-app/frontend/src/main.tsx", "folder::shadow-app/frontend/src/pages", "folder::shadow-app/frontend/src/utils"]),
  "file::shadow-app/frontend/src/App.tsx": node("file::shadow-app/frontend/src/App.tsx", "App.tsx", "file", "folder::shadow-app/frontend/src", ["function::App"]),
  "folder::shadow-app/frontend/src/api": node("folder::shadow-app/frontend/src/api", "api", "folder", "folder::shadow-app/frontend/src", ["file::shadow-app/frontend/src/api/ApiClient.ts", "file::shadow-app/frontend/src/api/HttpApiClient.ts"]),
  "file::shadow-app/frontend/src/api/ApiClient.ts": node("file::shadow-app/frontend/src/api/ApiClient.ts", "ApiClient.ts", "file", "folder::shadow-app/frontend/src/api", ["class::ApiClient"]),
  "file::shadow-app/frontend/src/api/HttpApiClient.ts": node("file::shadow-app/frontend/src/api/HttpApiClient.ts", "HttpApiClient.ts", "file", "folder::shadow-app/frontend/src/api", ["class::HttpApiClient"]),
  "folder::shadow-app/frontend/src/components": node("folder::shadow-app/frontend/src/components", "components", "folder", "folder::shadow-app/frontend/src", ["file::shadow-app/frontend/src/components/OrderList.tsx", "file::shadow-app/frontend/src/components/UserList.tsx"]),
  "file::shadow-app/frontend/src/components/OrderList.tsx": node("file::shadow-app/frontend/src/components/OrderList.tsx", "OrderList.tsx", "file", "folder::shadow-app/frontend/src/components", ["function::OrderList"]),
  "file::shadow-app/frontend/src/components/UserList.tsx": node("file::shadow-app/frontend/src/components/UserList.tsx", "UserList.tsx", "file", "folder::shadow-app/frontend/src/components", ["function::UserList"]),
  "folder::shadow-app/frontend/src/domain": node("folder::shadow-app/frontend/src/domain", "domain", "folder", "folder::shadow-app/frontend/src", ["file::shadow-app/frontend/src/domain/types.ts"]),
  "file::shadow-app/frontend/src/domain/types.ts": node("file::shadow-app/frontend/src/domain/types.ts", "types.ts", "file", "folder::shadow-app/frontend/src/domain", []),
  "file::shadow-app/frontend/src/main.tsx": node("file::shadow-app/frontend/src/main.tsx", "main.tsx", "file", "folder::shadow-app/frontend/src", ["function::bootstrap"]),
  "folder::shadow-app/frontend/src/pages": node("folder::shadow-app/frontend/src/pages", "pages", "folder", "folder::shadow-app/frontend/src", ["file::shadow-app/frontend/src/pages/Dashboard.tsx"]),
  "file::shadow-app/frontend/src/pages/Dashboard.tsx": node("file::shadow-app/frontend/src/pages/Dashboard.tsx", "Dashboard.tsx", "file", "folder::shadow-app/frontend/src/pages", ["function::Dashboard"]),
  "folder::shadow-app/frontend/src/utils": node("folder::shadow-app/frontend/src/utils", "utils", "folder", "folder::shadow-app/frontend/src", ["file::shadow-app/frontend/src/utils/formatting.ts"]),
  "file::shadow-app/frontend/src/utils/formatting.ts": node("file::shadow-app/frontend/src/utils/formatting.ts", "formatting.ts", "file", "folder::shadow-app/frontend/src/utils", ["function::formatCurrency"]),

  // Hand-authored demo nodes below — unlike the folder/file hierarchy above, real class/function
  // extraction from source isn't wired up yet (no bridge exists), so these exist purely to demo
  // the file -> class/function -> code drill-down in the UI.
  "class::EmailClient": node("class::EmailClient", "EmailClient", "class", "file::shadow-app/backend/clients/email_client.py", ["function::EmailClient.send", "function::EmailClient._format_subject"]),
  "function::EmailClient.send": node(
    "function::EmailClient.send",
    "send",
    "function",
    "class::EmailClient",
    [],
    {
      language: "python",
      params: "(self, to: str, subject: str, body: str) -> None",
      source: [
        "def send(self, to: str, subject: str, body: str) -> None:",
        "    message = self._format_subject(subject) + \"\\n\\n\" + body",
        "    self._smtp.sendmail(self._from_addr, [to], message)",
      ].join("\n"),
    },
  ),
  "function::EmailClient._format_subject": node(
    "function::EmailClient._format_subject",
    "_format_subject",
    "function",
    "class::EmailClient",
    [],
    {
      language: "python",
      params: "(self, subject: str) -> str",
      source: ["def _format_subject(self, subject: str) -> str:", '    return f"[shadow-app] {subject}"'].join(
        "\n",
      ),
    },
  ),
  "function::calculate_total": node(
    "function::calculate_total",
    "calculate_total",
    "function",
    "file::shadow-app/backend/domain/order_service.py",
    [],
    {
      language: "python",
      params: "(items: list[OrderItem]) -> float",
      source: [
        "def calculate_total(items: list[OrderItem]) -> float:",
        "    return sum(item.unit_price * item.quantity for item in items)",
      ].join("\n"),
    },
  ),
  "function::apply_discount": node(
    "function::apply_discount",
    "apply_discount",
    "function",
    "file::shadow-app/backend/domain/order_service.py",
    [],
    {
      language: "python",
      params: "(total: float, discount_pct: float) -> float",
      source: [
        "def apply_discount(total: float, discount_pct: float) -> float:",
        "    return total * (1 - discount_pct / 100)",
      ].join("\n"),
    },
  ),
  "class::PaymentClient": node("class::PaymentClient", "PaymentClient", "class", "file::shadow-app/backend/clients/payment_client.py", ["function::PaymentClient.charge", "function::PaymentClient.refund"]),
  "function::PaymentClient.charge": node(
    "function::PaymentClient.charge",
    "charge",
    "function",
    "class::PaymentClient",
    [],
    {
      language: "python",
      params: "(self, amount: float, card_token: str) -> str",
      source: [
        "def charge(self, amount: float, card_token: str) -> str:",
        "    return self._gateway.create_charge(amount, card_token)",
      ].join("\n"),
    },
  ),
  "function::PaymentClient.refund": node(
    "function::PaymentClient.refund",
    "refund",
    "function",
    "class::PaymentClient",
    [],
    {
      language: "python",
      params: "(self, charge_id: str) -> None",
      source: ["def refund(self, charge_id: str) -> None:", "    self._gateway.reverse_charge(charge_id)"].join(
        "\n",
      ),
    },
  ),
  "class::Settings": node("class::Settings", "Settings", "class", "file::shadow-app/backend/config.py", ["function::Settings.load"]),
  "function::Settings.load": node(
    "function::Settings.load",
    "load",
    "function",
    "class::Settings",
    [],
    {
      language: "python",
      params: "(cls) -> Settings",
      source: [
        "@classmethod",
        "def load(cls) -> \"Settings\":",
        "    return cls(",
        "        app_name=os.environ.get(\"APP_NAME\", cls.app_name),",
        "        debug=os.environ.get(\"DEBUG\", str(cls.debug)).lower() in {\"1\", \"true\", \"yes\"},",
        "    )",
      ].join("\n"),
    },
  ),
  "function::get_db": node(
    "function::get_db",
    "get_db",
    "function",
    "file::shadow-app/backend/dependencies.py",
    [],
    {
      language: "python",
      params: "() -> Iterator[Session]",
      source: ["def get_db() -> Iterator[Session]:", "    with SessionLocal() as session:", "        yield session"].join(
        "\n",
      ),
    },
  ),
  "function::get_current_user": node(
    "function::get_current_user",
    "get_current_user",
    "function",
    "file::shadow-app/backend/dependencies.py",
    [],
    {
      language: "python",
      params: "(token: str = Depends(oauth2_scheme)) -> User",
      source: [
        "def get_current_user(token: str = Depends(oauth2_scheme)) -> User:",
        "    return decode_access_token(token)",
      ].join("\n"),
    },
  ),
  "function::register_user": node(
    "function::register_user",
    "register_user",
    "function",
    "file::shadow-app/backend/domain/user_service.py",
    [],
    {
      language: "python",
      params: "(email: str, password: str) -> User",
      source: [
        "def register_user(email: str, password: str) -> User:",
        "    return UserRepository().save(User(email=email, password_hash=hash_password(password)))",
      ].join("\n"),
    },
  ),
  "function::authenticate_user": node(
    "function::authenticate_user",
    "authenticate_user",
    "function",
    "file::shadow-app/backend/domain/user_service.py",
    [],
    {
      language: "python",
      params: "(email: str, password: str) -> User | None",
      source: [
        "def authenticate_user(email: str, password: str) -> User | None:",
        "    user = UserRepository().find_by_email(email)",
        "    return user if user and verify_password(password, user.password_hash) else None",
      ].join("\n"),
    },
  ),
  "function::create_app": node(
    "function::create_app",
    "create_app",
    "function",
    "file::shadow-app/backend/main.py",
    [],
    {
      language: "python",
      params: "() -> FastAPI",
      source: [
        "def create_app() -> FastAPI:",
        "    app = FastAPI()",
        "    app.include_router(orders_router)",
        "    app.include_router(users_router)",
        "    return app",
      ].join("\n"),
    },
  ),
  "function::main": node(
    "function::main",
    "main",
    "function",
    "file::shadow-app/backend/main.py",
    [],
    {
      language: "python",
      params: "() -> None",
      source: ["def main() -> None:", "    uvicorn.run(create_app(), host=\"0.0.0.0\", port=8000)"].join("\n"),
    },
  ),
  "function::format_currency": node(
    "function::format_currency",
    "format_currency",
    "function",
    "file::shadow-app/backend/models/formatting.py",
    [],
    {
      language: "python",
      params: "(amount: float, currency: str = \"USD\") -> str",
      source: [
        "def format_currency(amount: float, currency: str = \"USD\") -> str:",
        '    return f"{amount:,.2f} {currency}"',
      ].join("\n"),
    },
  ),
  "class::Order": node("class::Order", "Order", "class", "file::shadow-app/backend/models/order.py", ["function::Order.total"]),
  "function::Order.total": node(
    "function::Order.total",
    "total",
    "function",
    "class::Order",
    [],
    {
      language: "python",
      params: "(self) -> float",
      source: ["def total(self) -> float:", "    return calculate_total(self.items)"].join("\n"),
    },
  ),
  "class::User": node("class::User", "User", "class", "file::shadow-app/backend/models/user.py", ["function::User.full_name"]),
  "function::User.full_name": node(
    "function::User.full_name",
    "full_name",
    "function",
    "class::User",
    [],
    {
      language: "python",
      params: "(self) -> str",
      source: ["def full_name(self) -> str:", '    return f"{self.first_name} {self.last_name}"'].join("\n"),
    },
  ),
  "class::BaseRepository": node("class::BaseRepository", "BaseRepository", "class", "file::shadow-app/backend/repositories/base.py", ["function::BaseRepository.get", "function::BaseRepository.save"]),
  "function::BaseRepository.get": node(
    "function::BaseRepository.get",
    "get",
    "function",
    "class::BaseRepository",
    [],
    {
      language: "python",
      params: "(self, entity_id: str) -> T | None",
      source: ["def get(self, entity_id: str) -> T | None:", "    return self._session.get(self.model, entity_id)"].join(
        "\n",
      ),
    },
  ),
  "function::BaseRepository.save": node(
    "function::BaseRepository.save",
    "save",
    "function",
    "class::BaseRepository",
    [],
    {
      language: "python",
      params: "(self, entity: T) -> T",
      source: ["def save(self, entity: T) -> T:", "    self._session.add(entity)", "    self._session.commit()", "    return entity"].join(
        "\n",
      ),
    },
  ),
  "class::OrderRepository": node("class::OrderRepository", "OrderRepository", "class", "file::shadow-app/backend/repositories/order_repository.py", ["function::OrderRepository.find_by_id"]),
  "function::OrderRepository.find_by_id": node(
    "function::OrderRepository.find_by_id",
    "find_by_id",
    "function",
    "class::OrderRepository",
    [],
    {
      language: "python",
      params: "(self, order_id: str) -> Order | None",
      source: ["def find_by_id(self, order_id: str) -> Order | None:", "    return self.get(order_id)"].join(
        "\n",
      ),
    },
  ),
  "class::UserRepository": node("class::UserRepository", "UserRepository", "class", "file::shadow-app/backend/repositories/user_repository.py", ["function::UserRepository.find_by_email"]),
  "function::UserRepository.find_by_email": node(
    "function::UserRepository.find_by_email",
    "find_by_email",
    "function",
    "class::UserRepository",
    [],
    {
      language: "python",
      params: "(self, email: str) -> User | None",
      source: [
        "def find_by_email(self, email: str) -> User | None:",
        "    return self._session.query(User).filter_by(email=email).first()",
      ].join("\n"),
    },
  ),
  "function::list_orders": node(
    "function::list_orders",
    "list_orders",
    "function",
    "file::shadow-app/backend/routers/orders_router.py",
    [],
    {
      language: "python",
      params: "(db: Session = Depends(get_db)) -> list[Order]",
      source: [
        "@router.get(\"/orders\")",
        "def list_orders(db: Session = Depends(get_db)) -> list[Order]:",
        "    return OrderRepository(db).list_all()",
      ].join("\n"),
    },
  ),
  "function::create_order": node(
    "function::create_order",
    "create_order",
    "function",
    "file::shadow-app/backend/routers/orders_router.py",
    [],
    {
      language: "python",
      params: "(payload: OrderCreate, db: Session = Depends(get_db)) -> Order",
      source: [
        "@router.post(\"/orders\")",
        "def create_order(payload: OrderCreate, db: Session = Depends(get_db)) -> Order:",
        "    return OrderRepository(db).save(Order(**payload.dict()))",
      ].join("\n"),
    },
  ),
  "function::list_users": node(
    "function::list_users",
    "list_users",
    "function",
    "file::shadow-app/backend/routers/users_router.py",
    [],
    {
      language: "python",
      params: "(db: Session = Depends(get_db)) -> list[User]",
      source: [
        "@router.get(\"/users\")",
        "def list_users(db: Session = Depends(get_db)) -> list[User]:",
        "    return UserRepository(db).list_all()",
      ].join("\n"),
    },
  ),
  "function::create_user": node(
    "function::create_user",
    "create_user",
    "function",
    "file::shadow-app/backend/routers/users_router.py",
    [],
    {
      language: "python",
      params: "(payload: UserCreate, db: Session = Depends(get_db)) -> User",
      source: [
        "@router.post(\"/users\")",
        "def create_user(payload: UserCreate, db: Session = Depends(get_db)) -> User:",
        "    return register_user(payload.email, payload.password)",
      ].join("\n"),
    },
  ),
  "function::App": node(
    "function::App",
    "App",
    "function",
    "file::shadow-app/frontend/src/App.tsx",
    [],
    {
      language: "typescript",
      params: "(): JSX.Element",
      source: [
        "function App(): JSX.Element {",
        "  return (",
        "    <Dashboard />",
        "  );",
        "}",
      ].join("\n"),
    },
  ),
  "class::ApiClient": node("class::ApiClient", "ApiClient", "class", "file::shadow-app/frontend/src/api/ApiClient.ts", ["function::ApiClient.fetchOrders"]),
  "function::ApiClient.fetchOrders": node(
    "function::ApiClient.fetchOrders",
    "fetchOrders",
    "function",
    "class::ApiClient",
    [],
    {
      language: "typescript",
      params: "(): Promise<Order[]>",
      source: ["abstract fetchOrders(): Promise<Order[]>;"].join("\n"),
    },
  ),
  "class::HttpApiClient": node("class::HttpApiClient", "HttpApiClient", "class", "file::shadow-app/frontend/src/api/HttpApiClient.ts", ["function::HttpApiClient.fetchOrders"]),
  "function::HttpApiClient.fetchOrders": node(
    "function::HttpApiClient.fetchOrders",
    "fetchOrders",
    "function",
    "class::HttpApiClient",
    [],
    {
      language: "typescript",
      params: "(): Promise<Order[]>",
      source: [
        "async fetchOrders(): Promise<Order[]> {",
        "  const res = await fetch(`${this.baseUrl}/orders`);",
        "  return res.json();",
        "}",
      ].join("\n"),
    },
  ),
  "function::OrderList": node(
    "function::OrderList",
    "OrderList",
    "function",
    "file::shadow-app/frontend/src/components/OrderList.tsx",
    [],
    {
      language: "typescript",
      params: "({ orders }: { orders: Order[] }): JSX.Element",
      source: [
        "function OrderList({ orders }: { orders: Order[] }): JSX.Element {",
        "  return <ul>{orders.map((o) => <li key={o.id}>{o.id}</li>)}</ul>;",
        "}",
      ].join("\n"),
    },
  ),
  "function::UserList": node(
    "function::UserList",
    "UserList",
    "function",
    "file::shadow-app/frontend/src/components/UserList.tsx",
    [],
    {
      language: "typescript",
      params: "({ users }: { users: User[] }): JSX.Element",
      source: [
        "function UserList({ users }: { users: User[] }): JSX.Element {",
        "  return <ul>{users.map((u) => <li key={u.id}>{u.fullName}</li>)}</ul>;",
        "}",
      ].join("\n"),
    },
  ),
  "function::bootstrap": node(
    "function::bootstrap",
    "bootstrap",
    "function",
    "file::shadow-app/frontend/src/main.tsx",
    [],
    {
      language: "typescript",
      params: "(): void",
      source: [
        "function bootstrap(): void {",
        '  createRoot(document.getElementById("root")!).render(<App />);',
        "}",
      ].join("\n"),
    },
  ),
  "function::Dashboard": node(
    "function::Dashboard",
    "Dashboard",
    "function",
    "file::shadow-app/frontend/src/pages/Dashboard.tsx",
    [],
    {
      language: "typescript",
      params: "(): JSX.Element",
      source: [
        "function Dashboard(): JSX.Element {",
        "  return (",
        "    <>",
        "      <OrderList orders={useOrders()} />",
        "      <UserList users={useUsers()} />",
        "    </>",
        "  );",
        "}",
      ].join("\n"),
    },
  ),
  "function::formatCurrency": node(
    "function::formatCurrency",
    "formatCurrency",
    "function",
    "file::shadow-app/frontend/src/utils/formatting.ts",
    [],
    {
      language: "typescript",
      params: "(amount: number, currency = \"USD\"): string",
      source: [
        "function formatCurrency(amount: number, currency = \"USD\"): string {",
        "  return new Intl.NumberFormat(\"en-US\", { style: \"currency\", currency }).format(amount);",
        "}",
      ].join("\n"),
    },
  ),
};

// Populate whole-file `source` on file-level nodes, and whole-class `source` on class-level
// nodes, by concatenating descendant function source (recursing through classes into their
// methods), so "Show Full File"/"Show Class" have something to render without hand-duplicating
// every function body above.
function collectDescendantSource(nodeId: string): string {
  const fixtureNode = FIXTURE_NODES[nodeId];
  if (!fixtureNode) return "";
  if (fixtureNode.level === "function") return fixtureNode.source ?? "";
  return fixtureNode.children
    .map(collectDescendantSource)
    .filter((source) => source.length > 0)
    .join("\n\n");
}

function languageForFileName(name: string): string | undefined {
  if (name.endsWith(".py")) return "python";
  if (name.endsWith(".ts") || name.endsWith(".tsx")) return "typescript";
  return undefined;
}

for (const fixtureNode of Object.values(FIXTURE_NODES)) {
  if (
    (fixtureNode.level === "file" || fixtureNode.level === "class") &&
    fixtureNode.children.length > 0 &&
    !fixtureNode.source
  ) {
    const source = collectDescendantSource(fixtureNode.node_id);
    if (source) {
      fixtureNode.source = source;
      fixtureNode.language =
        fixtureNode.level === "file"
          ? languageForFileName(fixtureNode.name)
          : languageForFileName(FIXTURE_NODES[fixtureNode.parent_id ?? ""]?.name ?? "");
    }
  }
}
