"""Regenerates web/src/engine-client/fixtures.ts from a plain filesystem walk over examples/.

Usage: poetry run python scripts/export_examples_fixture.py

Builds a folder/file-only hierarchy (no symbol parsing, no LLM) mirroring the real directory
structure under examples/: every directory and file at any depth gets its own node. This
deliberately skips GraphEngine/GraphBuilder -- their Pillar/Component levels only capture one level
of directory nesting (_top_level_dir), which would flatten e.g. examples/shadow-app/backend/routers/
onto the same box as examples/shadow-app/backend/config.py.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
EXAMPLES_ROOT = REPO_ROOT / "examples"
OUTPUT_PATH = REPO_ROOT / "web" / "src" / "engine-client" / "fixtures.ts"
ROOT_ID = "root"

_SKIP_NAMES = {".git", "__pycache__", "node_modules", ".venv", "dist", "build"}


def _should_skip(entry: Path) -> bool:
    return entry.name in _SKIP_NAMES or entry.name.startswith(".")


def build_frontend_tree() -> dict[str, dict]:
    tree: dict[str, dict] = {}

    def add(node_id: str, name: str, level: str, parent_id: str | None) -> None:
        tree[node_id] = {"name": name, "level": level, "parent_id": parent_id, "children": []}

    add(ROOT_ID, "examples", "folder", None)

    def walk(directory: Path, parent_id: str) -> None:
        for entry in sorted(directory.iterdir(), key=lambda p: p.name):
            if _should_skip(entry):
                continue
            rel_path = entry.relative_to(EXAMPLES_ROOT).as_posix()
            if entry.is_dir():
                node_id = f"folder::{rel_path}"
                add(node_id, entry.name, "folder", parent_id)
                walk(entry, node_id)
            elif entry.is_file():
                add(f"file::{rel_path}", entry.name, "file", parent_id)

    walk(EXAMPLES_ROOT, ROOT_ID)

    for node_id, data in tree.items():
        if data["parent_id"] is not None:
            tree[data["parent_id"]]["children"].append(node_id)
    for data in tree.values():
        data["children"].sort(key=lambda cid: tree[cid]["name"])

    return tree


def _traversal_order(tree: dict[str, dict]) -> list[str]:
    order: list[str] = []
    stack = [ROOT_ID]
    while stack:
        node_id = stack.pop(0)
        order.append(node_id)
        stack = tree[node_id]["children"] + stack
    return order


def render_ts(tree: dict[str, dict]) -> str:
    lines = [
        'import type { HierarchyLevel, HierarchyNodeRef } from "../state/types";',
        "",
        "export interface FixtureNode extends HierarchyNodeRef {",
        "  children: string[];",
        "}",
        "",
        "function node(",
        "  node_id: string,",
        "  name: string,",
        "  level: HierarchyLevel,",
        "  parent_id: string | null,",
        "  children: string[],",
        "): FixtureNode {",
        "  return {",
        "    node_id,",
        "    name,",
        "    level,",
        "    parent_id,",
        "    has_children: children.length > 0,",
        "    child_count: children.length,",
        "    children,",
        "  };",
        "}",
        "",
        "/**",
        " * Folder/file fixture hierarchy, generated by `scripts/export_examples_fixture.py`",
        " * from a plain filesystem walk over `examples/` -- not hand-authored. Re-run it after",
        " * adding or changing files under `examples/`.",
        " */",
        "export const FIXTURE_NODES: Record<string, FixtureNode> = {",
    ]
    for node_id in _traversal_order(tree):
        data = tree[node_id]
        parent_js = "null" if data["parent_id"] is None else json.dumps(data["parent_id"])
        children_js = "[" + ", ".join(json.dumps(c) for c in data["children"]) + "]"
        lines.append(
            f'  {json.dumps(node_id)}: node({json.dumps(node_id)}, {json.dumps(data["name"])}, '
            f'"{data["level"]}", {parent_js}, {children_js}),'
        )
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    tree = build_frontend_tree()
    OUTPUT_PATH.write_text(render_ts(tree))
    print(f"Wrote {len(tree)} nodes to {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
